CI: check go vendor in goreleaser

diff --git a/.github/workflows/goreleaser.yml b/.github/workflows/goreleaser.yml
--- a/.github/workflows/goreleaser.yml
+++ b/.github/workflows/goreleaser.yml
@@ -34,6 +34,12 @@ jobs:
 
       - name: tests modules
         run: |
+          go mod vendor
+          if [ ! -z "$(git status --porcelain)" ]; then
+            echo "::error::vendor directory if not synced with go.mod, please run go mod vendor"
+            exit 1
+          fi
+
           go mod tidy
           if [ ! -z "$(git status --porcelain)" ]; then
             echo "::error::modules are not tidy, please run go mod tidy"
